services:
  db:
    image: postgres:15
    container_name: image_cluster_db
    restart: always
    environment:
      - POSTGRES_USER=cluster_user
      - POSTGRES_PASSWORD=secure_password
      - POSTGRES_DB=image_db
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: